# Generated by Django 5.2.8 on 2025-11-24 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_group_task',
        ),
    ]
