# Generated by Django 5.2.8 on 2025-11-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoer', '0002_remove_task_is_group_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
