# Generated by Django 5.2.8 on 2025-11-28 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.CharField(max_length=20, unique=True)),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('grupo', models.CharField(blank=True, max_length=100, null=True)),
                ('cuil', models.CharField(max_length=20, unique=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20, null=True)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=200, null=True)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('ingreso_empresa', models.DateField(blank=True, null=True)),
                ('ingreso_pct', models.DateField(blank=True, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
